recipe: "regression/v1"
# Specifies the name of the column containing targets / labels for model training and evaluation
target_col: math_score
primary_metric: r2_score
steps:
  ingest: {{INGEST_CONFIG}}
  split:
    split_ratios: {{SPLIT_RATIOS|default([0.75, 0.125, 0.125])}}
  transform:
    using: custom
    transformer_method: transformer_fn
  train: {{TRAIN_CONFIG}}
  evaluate:
    # Sets performance thresholds that a trained model must meet in order to be eligible for
    # registration to the MLflow Model Registry
    validation_criteria:
      - metric: r2_score
        threshold: 0.7
  register:
    # Indicates whether or not a model that fails to meet performance thresholds should still
    # be registered to the MLflow Model Registry
    allow_non_validated_model: false
  ingest_scoring: {{INGEST_SCORING_CONFIG}}
  predict:
    output: {{PREDICT_OUTPUT_CONFIG}}
    # model_uri: "models/model.pkl"

# Defines custom performance metrics to compute during model training and evaluation
custom_metrics:
  - name: r2_score
    # Specifies the name of the function in `steps/custom_metrics.py` to use to compute the metric
    function: calculate_r2_score
    greater_is_better: True
