name: Build and deploy an app to AKS

on:
  push:
    branches: main

env:
  TF_VAR_resource_group_location: ${{ secrets.resource_group_location }}
  TF_VAR_resource_group_name: ${{ secrets.resource_group_name }}
  TF_VAR_aks_service_principal_app_id: ${{ secrets.aks_service_principal_app_id }}
  TF_VAR_aks_service_principal_client_secret: ${{ secrets.aks_service_principal_client_secret }}
  KUBECONFIG: ${{ secrets.KUBECONFIG }}
  tenant: ${{ secrets.tenant }}
  subscription_id: ${{ secrets.subscription_id }}

jobs:
  azLogin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          auth-type: IDENTITY
