name: Build and deploy an app to AKS

on:
  push:
    branches: main

jobs:
  deploy:
    name: Deploy into Azure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate SSH Key
        run: |
          ssh-keygen -t rsa -N '' -f /home/runner/.ssh/id_rsa

      - uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init -backend-config=tf-backend.hcl

      - name: Import Azure Resource Group
        run: terraform import azurerm_resource_group.k8s ${{ secrets.AZURE_RESOURCE_ID }}
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false
        env:
          TF_VAR_resource_group_location: ${{ vars.RG_LOCATION }}
          TF_VAR_resource_group_name: ${{ vars.RG_NAME }}
          TF_VAR_aks_service_principal_app_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_aks_service_principal_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
