name: Build and deploy an app to AKS

on:
  push:
    branches: main

jobs:
  terraformSetup:
    name: Terraform Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate SSH Key
        run: |
          ssh-keygen -t rsa -N ''

      - uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
            
      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -input=false
        env:
          TF_VAR_resource_group_location: ${{ vars.RG_LOCATION }}
          TF_VAR_resource_group_name: ${{ vars.RG_NAME }}
          TF_VAR_aks_service_principal_app_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_aks_service_principal_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
