name: Build and deploy an app to AKS

on:
  push:
    branches: main

jobs:
  azLogin:
    name: Login Azure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}